### ISSUE TITLE
/ in a string autocloses the enclosing tag

### ISSUE THREAD

**Issue by Sunjammer** [MiracleBlue/autoclose-tags#2]
`<WebView Url="http:/>"/>`

It's a bad scene :(

**Comment by MiracleBlue** [comment]
We've got a pr merged that I'll publish asap, should solve the issue. Will update when published.

**Comment by MiracleBlue** [comment]
Looks like this is working in the new version, which is 0.2.2.  Please update and try that, and feel free to re-open if it's still broken for you in the new version :)
