### ISSUE TITLE
A closing tag will be generated when JavaScript arrow function is used

### ISSUE THREAD

**Issue by oneill-c** [MiracleBlue/autoclose-tags#6]
When you use an arrow function 

e.g. 

(someVar) => { }

when you type the '>' character in the arrow function declaration, the autoclose-tags library seems to pick this up as an element and will generate a closing tag which should not happen.

My specific example where this was witnessed:

<button onClick={ () => this.onDismiss(item.objectID) } type="button">Dismiss</button>

Versions:

Windows 10 Home x64
Atom: 1.15.0
autoclose-tags: 0.2.1

**Comment by MiracleBlue** [comment]
Goodness gracious, github hasn't been sending me any notifications for the issues that have been popping up. I've just merged a pr from someone that could fix this, I'll publish it in the coming days, let's see if that sorts it

**Comment by MiracleBlue** [comment]
Latest version, 0.2.2, seems to have fixed this issue, so I'll close this bug but please re-open if its still broken after updating.
