### ISSUE TITLE
Twice indents.

### ISSUE THREAD

**Issue by ikngtty** [MiracleBlue/autoclose-tags#7]
When I type `>`, a closing tag `</div>` is inserted automatically.
And then I type `Enter` key,  the text is as below:

```
<div>
    [I]
</div>
```

※ `[I]` is the cursor.

At this time, a 2 spaces indent is expected, but 4 spaces are inserted actually.

My environment:
```
OS: macOS High Sierra
Atom: 1.26.1
```

This bug may not occur before. (I'm not too sure.)
It may occur at only newer Atom.

**Comment by MiracleBlue** [comment]
Many thanks for your PR!  I've merged it in :) I'll have to try and remember how to do a new release.
