### ISSUE TITLE
Uncaught TypeError: this.action.disposalAction is not a function

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [MiracleBlue/autoclose-tags#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [autoclose-tags](https://github.com/MiracleBlue/autoclose-tags) package 0.2.2

### Stack Trace

Uncaught TypeError: this.action.disposalAction is not a function

```
At C:\Users\Admin\.atom\packages\autoclose-tags\lib\autoclose.coffee:39

TypeError: this.action.disposalAction is not a function
    at Object._paneItemChanged (/packages/autoclose-tags/lib/autoclose.coffee:39:29)
    at /packages/autoclose-tags/lib/autoclose.coffee:26:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didActivatePaneContainer (~/AppData/Local/atom/app-1.27.1/resources/app/src/workspace.js:430:26)
    at Dock.subscriptions.CompositeDisposable.paneContainer.onDidActivatePane (~/AppData/Local/atom/app-1.27.1/resources/app/src/dock.js:62:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.27.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.27.1/resources/app/src/pane-container.js:265:24)
    at Pane.activate (~/AppData/Local/atom/app-1.27.1/resources/app/src/pane.js:1018:46)
    at Pane.focus (~/AppData/Local/atom/app-1.27.1/resources/app/src/pane.js:401:23)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
```

### Non-Core Packages

```
autoclose-tags 0.2.2 
esformatter 2.3.0 
jade-beautify 0.1.5 
nuclide 0.271.0 
pigments 0.40.2 
react-es6-snippets 0.3.0 
react-native-snippets 0.3.0 
react-native-snippets-horse 2.0.0 
react-snippets 1.0.1 
```

**Comment by Starystars67** [comment]
I am also getting this error and its damn annoying poping up every time i open a file

**Comment by ThomazMancini** [comment]
"Eu também estou recebendo este erro e seu maldito irritante pop up toda vez que eu abrir um arquivo"
Estamos com este problema horrível amigo, por favor alguém nos ajude!

**Comment by redferret** [comment]
I am also getting this

**Comment by r0ckarong** [comment]
Happening here too. Atom 1.30.0 on openSUSE Tumbleweed.

**Comment by redferret** [comment]
Is this going to be taken care of? Is there a way to at least shut off these popups?

**Comment by redferret** [comment]
Is there a way to at least turn off the popups? It's really disturbing.

**Comment by Starystars67** [comment]
I think we can say that the dev is inactive :(

**Comment by ThomazMancini** [comment]
Staff our friend ikngtty found the solution to this error, I tested it here and it worked properly, stopped appearing those annoying inssues and returned to function functionality, thank you dear ikngtty !!
https://github.com/MiracleBlue/autoclose-tags/pull/11/commits/07b9b0d0fdaa714f2cb9ec8b61c4ae7700fb3750

**Comment by rolzing** [comment]
> I am also getting this error and its damn annoying poping up every time i open a file

same here

MAC OS X 10.14.1
ATOM 1.32.2

**Comment by MiracleBlue** [comment]
So sorry everyone, for some reason github isn't notifying me when people post issues :( so I have to check this regularly.

I'm gonna look into it now.  I know I'm late >.<

**Comment by MiracleBlue** [comment]
@Starystars67 @redferret @nilaybrahmbhatt I've merged a PR that seems like it will fix the issue, and I'll have a go publishing.  If I could ask a favor from you all, if you have any new issues or ever want to grab my attention, please just tag me by my username :) I can't seem to understand why github doesn't notify me when there are new issues like this one, but if you try that hopefully that will make sure I do get a notification. If anyone has any advice on how to configure github to notify me, please let me know!

**Comment by MiracleBlue** [comment]
Fiiiiinally got it published.  New version is online as 0.2.4 (I know, should be 0.2.3 but I spent a while messing around with APM to make it auth).  Please give it a try and if this is still an issue, reopen the issue and tag me in a comment :)

Sorry again everyone.  Hopefully I can find a way to get these notifications happening, too.

**Comment by ikngtty** [comment]
@MiracleBlue Is your setting for this repository "Watching"?

![image](https://user-images.githubusercontent.com/22126639/52616404-c3405700-2edb-11e9-8e04-1a2372e9c075.png)

**Comment by MiracleBlue** [comment]
@ikngtty Ahhh!  It was not watching!  I've changed it now, hopefully that fixes it.  Thanks so much!

**Comment by Starystars67** [comment]
Not seen the issue recently, seems to have resolved it thank you!

**Comment by bagatelli** [comment]
I keep seen the issue again. It's incredibly annoying. Can you please look into this again?

**Comment by MiracleBlue** [comment]
Sure, did you try the latest version? I've been running it since the fix on
latest atom and haven't had any such issues yet. Could you double check the
version for me?

**Comment by bagatelli** [comment]
Oh. Nevermind. My apologies. It was another issue related to atom. It works fine now. Thank you!
